import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { matchProducts, getBleachProducts, getAftercareProducts, type ProductRecommendation } from "@/engine/productMatcher";
import type { HairState, SimulationResult } from "@/types";
import { ShoppingBag, Scissors, CheckCircle2, Copy, Check, Package } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

interface Props {
    result: Extract<SimulationResult, { status: "success" }>;
    hairState: HairState;
}

export function ShoppingList({ result, hairState }: Props) {
    const [copied, setCopied] = useState(false);
    
    const dyeInput = result.appliedInput;
    const products = matchProducts(
        result.achievableLevel,
        dyeInput.targetTone,
        hairState.hairLength,
        hairState.hairThickness
    );

    const bleachProducts = dyeInput.bleachEnabled
        ? getBleachProducts(
            dyeInput.bleachLifts || 1,
            hairState.hairLength,
            hairState.hairThickness
        )
        : null;

    const aftercare = getAftercareProducts();
    
    // Generate plain text shopping list
    const generateShoppingListText = () => {
        let text = "🛒 DYECODE SHOPPING LIST\n\n";
        
        if (bleachProducts) {
            text += "STEP 1: PRE-LIGHTENING\n";
            text += `• ${bleachProducts.quantity.boxes}x Powder Bleach/Lightener\n`;
            if (bleachProducts.developer) {
                text += `• 1x ${bleachProducts.developer.volume} Volume Developer (${bleachProducts.developer.size})\n`;
            }
            text += "\n";
        }
        
        if (products) {
            text += bleachProducts ? "STEP 2: COLOR APPLICATION\n" : "COLOR APPLICATION\n";
            text += `• ${products.quantity.boxes}x Hair Dye - Level ${products.dye.level} ${products.dye.tone.charAt(0).toUpperCase() + products.dye.tone.slice(1)} Tone\n`;
            if (products.developer) {
                text += `• 1x ${products.developer.volume} Volume Developer (${products.developer.size})\n`;
            }
            text += "\n";
        }
        
        text += "AFTERCARE\n";
        text += "• Purple/Blue Toning Shampoo (for blonde/ash tones)\n";
        text += "• Bond Repair Treatment (weekly)\n";
        text += "• Color-Safe Conditioner (daily)\n";
        
        text += "\n\nTOOLS NEEDED\n";
        ["Gloves", "Mixing bowl", "Brush", "Hair clips", "Timer", "Old towel"].forEach(tool => {
            text += `• ${tool}\n`;
        });
        
        text += "\n✨ Generated by Dyecode - dyecode.app";
        
        return text;
    };
    
    const copyShoppingList = () => {
        const text = generateShoppingListText();
        navigator.clipboard.writeText(text).then(() => {
            setCopied(true);
            toast.success("Shopping list copied to clipboard!");
            setTimeout(() => setCopied(false), 2000);
        }).catch(() => {
            toast.error("Failed to copy shopping list");
        });
    };

    if (!products && !bleachProducts) {
        return (
            <Card className="w-full max-w-2xl bg-zinc-50 dark:bg-zinc-900 shadow-none border-dashed">
                <CardContent className="pt-6 text-center">
                    <p className="text-sm text-zinc-500">No specific product matches found for this simulation. consult a professional for custom color mixing.</p>
                </CardContent>
            </Card>
        );
    }

    return (
        <Card className="w-full   border-zinc-200 dark:border-white/5 shadow-sm rounded-[24px] overflow-hidden">
            <CardHeader className="bg-zinc-50 dark:bg-white/5 border-b border-zinc-200 dark:border-white/5 px-8 py-6">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-[#f49d25] flex items-center justify-center">
                            <ShoppingBag className="w-5 h-5 text-white" />
                        </div>
                        <div>
                            <CardTitle className="text-lg">Shopping List</CardTitle>
                            <CardDescription className="text-xs">Everything you need to achieve this prediction</CardDescription>
                        </div>
                    </div>
                    <Button
                        onClick={copyShoppingList}
                        variant="outline"
                        size="sm"
                        className="flex items-center gap-2 text-xs"
                    >
                        {copied ? (
                            <>
                                <Check className="w-3.5 h-3.5" />
                                Copied!
                            </>
                        ) : (
                            <>
                                <Copy className="w-3.5 h-3.5" />
                                Copy List
                            </>
                        )}
                    </Button>
                </div>
            </CardHeader>
            <CardContent className="p-0">
                <div className="divide-y divide-zinc-200 dark:divide-white/5">
                    {/* Section: Pre-Lightening */}
                    {bleachProducts && (
                        <div className="p-8">
                            <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f49d25] mb-6 flex items-center gap-2">
                                <span className="w-4 h-px bg-[#f49d25]"></span> Step 1: Pre-Lightening
                            </h3>
                            <div className="grid gap-4 sm:grid-cols-2">
                                <ColorGuideItem
                                    title="Powder Bleach/Lightener"
                                    description="Look for powder bleach or lightening powder at any beauty supply store"
                                    quantity={`${bleachProducts.quantity.boxes}x box(es)`}
                                    searchTerms={["Powder bleach", "Lightener", "Bleach powder"]}
                                />
                                {bleachProducts.developer && (
                                    <ColorGuideItem
                                        title={`${bleachProducts.developer.volume} Volume Developer`}
                                        description="Cream developer to mix with bleach"
                                        quantity={`1x ${bleachProducts.developer.size} bottle`}
                                        searchTerms={[`${bleachProducts.developer.volume} vol developer`, `${bleachProducts.developer.volume} volume peroxide`]}
                                    />
                                )}
                            </div>
                        </div>
                    )}

                    {/* Section: Color Application */}
                    {products && (
                        <div className="p-8">
                            <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f49d25] mb-6 flex items-center gap-2">
                                <span className="w-4 h-px bg-[#f49d25]"></span> {bleachProducts ? "Step 2: Color Application" : "Color Application"}
                            </h3>
                            <div className="grid gap-4 sm:grid-cols-2">
                                <ColorGuideItem
                                    title={`Level ${products.dye.level} ${products.dye.tone.charAt(0).toUpperCase() + products.dye.tone.slice(1)} Tone`}
                                    description={`Look for hair dye labeled as Level ${products.dye.level} with ${products.dye.tone} tones`}
                                    quantity={`${products.quantity.boxes}x box(es)`}
                                    searchTerms={[
                                        `Level ${products.dye.level}`,
                                        `${products.dye.level}${products.dye.tone.charAt(0).toUpperCase()}`,
                                        getToneName(products.dye.level, products.dye.tone)
                                    ]}
                                />
                                {products.developer && (
                                    <ColorGuideItem
                                        title={`${products.developer.volume} Volume Developer`}
                                        description="Cream developer to activate the hair dye"
                                        quantity={`1x ${products.developer.size} bottle`}
                                        searchTerms={[`${products.developer.volume} vol developer`, `${products.developer.volume} volume peroxide`]}
                                    />
                                )}
                            </div>
                        </div>
                    )}

                    {/* Section: Aftercare */}
                    <div className="p-8 bg-zinc-50/50 dark:bg-black/20">
                        <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-zinc-500 mb-6 flex items-center gap-2">
                            <span className="w-4 h-px bg-zinc-500"></span> Essential Aftercare
                        </h3>
                        <div className="grid gap-4 sm:grid-cols-2">
                            <div className="flex flex-col p-4 bg-white dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-white/5">
                                <span className="text-xs font-bold text-zinc-900 dark:text-zinc-100 mb-2">Purple/Blue Toning Shampoo</span>
                                <p className="text-[10px] text-zinc-500 mb-3">Neutralizes yellow/brassy tones in blonde and ash colors</p>
                                <div className="mt-auto flex items-center gap-2 text-[9px] font-bold uppercase tracking-tight text-zinc-400">
                                    <CheckCircle2 className="w-3 h-3 text-[#f49d25]" />
                                    Use 2x per week
                                </div>
                            </div>
                            <div className="flex flex-col p-4 bg-white dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-white/5">
                                <span className="text-xs font-bold text-zinc-900 dark:text-zinc-100 mb-2">Bond Repair Treatment</span>
                                <p className="text-[10px] text-zinc-500 mb-3">Repairs broken bonds from chemical processing</p>
                                <div className="mt-auto flex items-center gap-2 text-[9px] font-bold uppercase tracking-tight text-zinc-400">
                                    <CheckCircle2 className="w-3 h-3 text-[#f49d25]" />
                                    Use 1x per week
                                </div>
                            </div>
                            <div className="flex flex-col p-4 bg-white dark:bg-zinc-900 rounded-2xl border border-zinc-200 dark:border-white/5">
                                <span className="text-xs font-bold text-zinc-900 dark:text-zinc-100 mb-2">Color-Safe Conditioner</span>
                                <p className="text-[10px] text-zinc-500 mb-3">Maintains color vibrancy and hair moisture</p>
                                <div className="mt-auto flex items-center gap-2 text-[9px] font-bold uppercase tracking-tight text-zinc-400">
                                    <CheckCircle2 className="w-3 h-3 text-[#f49d25]" />
                                    Use after every wash
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Section: Tools */}
                    <div className="p-8">
                        <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-zinc-500 mb-6 flex items-center gap-2">
                            <span className="w-4 h-px bg-zinc-500"></span> Tools Needed
                        </h3>
                        <div className="flex flex-wrap gap-2">
                            {["Gloves", "Mixing bowl", "Brush", "Hair clips", "Timer", "Old towel"].map(tool => (
                                <div key={tool} className="px-3 py-1.5 rounded-full bg-zinc-100 dark:bg-zinc-800 text-[10px] font-bold text-zinc-600 dark:text-zinc-400 border border-zinc-200 dark:border-white/5 flex items-center gap-2">
                                    <Scissors className="w-3 h-3" />
                                    {tool}
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Footer: Summary */}
                <div className="p-8 bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-950">
                    <div className="flex flex-col items-center text-center gap-3">
                        <p className="text-sm opacity-80">
                            Search for these items at any beauty supply store, drugstore, or online retailer
                        </p>
                    </div>
                </div>
            </CardContent>
        </Card>
    );
}

// Helper function to get descriptive tone names
function getToneName(level: number, tone: string): string {
    const toneMap: Record<string, string> = {
        neutral: "Natural",
        ash: "Ash/Cool",
        gold: "Golden/Warm",
        red: "Red",
        violet: "Violet"
    };
    
    const levelMap: Record<number, string> = {
        1: "Black",
        2: "Darkest Brown",
        3: "Dark Brown",
        4: "Medium Brown",
        5: "Light Brown",
        6: "Dark Blonde",
        7: "Medium Blonde",
        8: "Light Blonde",
        9: "Very Light Blonde",
        10: "Lightest Blonde"
    };
    
    return `${levelMap[level] || `Level ${level}`} ${toneMap[tone] || tone}`;
}

function ColorGuideItem({ title, description, quantity, searchTerms }: { 
    title: string, 
    description: string, 
    quantity: string, 
    searchTerms: string[] 
}) {
    return (
        <div className="group flex items-start gap-4 p-4 bg-white dark:bg-zinc-900 rounded-xl border border-zinc-200 dark:border-white/5 hover:border-[#f49d25]/30 hover:shadow-sm transition-all">
            {/* Product Icon */}
            <div className="w-12 h-12 rounded-lg bg-[#f49d25]/10 flex items-center justify-center shrink-0">
                <Package className="w-6 h-6 text-[#f49d25]" />
            </div>
            
            <div className="flex-1 min-w-0">
                <div className="mb-2">
                    <h4 className="text-sm font-bold text-zinc-900 dark:text-zinc-100 leading-tight">{title}</h4>
                    <p className="text-[10px] text-zinc-500 mt-1">{description}</p>
                </div>
                
                <div className="space-y-2">
                    <div className="flex items-center gap-2">
                        <span className="text-[9px] font-bold text-zinc-400 uppercase">Quantity:</span>
                        <span className="text-[10px] font-bold text-zinc-600 dark:text-zinc-300">{quantity}</span>
                    </div>
                    
                    <div>
                        <span className="text-[9px] font-bold text-zinc-400 uppercase block mb-1">Search for:</span>
                        <div className="flex flex-wrap gap-1">
                            {searchTerms.map((term, idx) => (
                                <span
                                    key={idx}
                                    className="px-2 py-0.5 rounded-md bg-[#f49d25]/10 text-[9px] font-bold text-[#f49d25]"
                                >
                                    {term}
                                </span>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
